---
abstract: 'Check Taiwan Esun bank info'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Finance::Bank::Esun::TW
name: Finance-Bank-Esun-TW
no_index:
  directory:
    - inc
    - t
requires:
  HTML::TableExtract: 1.5
  List::MoreUtils: 0
  Text::Trim: 0
  WWW::Mechanize: 1.5
  perl: 5.8.0
version: 0.01
